yourTrip/Controllers/TripController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using yourTrip.Models;
using yourTrip.Services;

using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Configuration;

namespace yourTrip.Controllers
{
    public class TripController : Controller
    {
        static HttpClient client = new HttpClient();        

        private TripRepository _repo;

        public TripController()
        {
            _repo = new TripRepository();
        }

        // GET: Trip
        public ActionResult Index(bool future = true)
        {
            try
            {
                ViewBag.IsFuture = future ? "1" : "0";
                if (Request.IsAuthenticated)
                {
                    IList<TripModels> trips = _repo.Get(GetUserId(), future);
                    TripModels trip = _repo.GetNextTrip(GetUserId());
                    if (trip != null && trip.Id > 0)
                    {
                        ViewBag.Date = trip.Departure.ToString("yyyy/MM/dd");
                        ViewBag.TripName = trip.Name;
                    }

                    return View(trips);
                }
            }
            catch(Exception ex)
            {
                //LOG
            }
            return View();
        }

        // GET: Trip/Details/5
        public ActionResult Details(int id)
        {
            TripModels trip = _repo.Get(id);
            ViewBag.Trip = trip;
            ViewBag.Date = trip.Departure.ToString("yyyy/MM/dd");

            return View(trip);
        }

        // GET: Trip/Create
        public ActionResult Create()
        {
            ViewBag.HasErrors = false;
            ViewBag.Trip = _repo.GetNextTrip(GetUserId());
            return View();
        }

        // POST: Trip/Create
        [HttpPost]
        public ActionResult Create(TripModels model)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    //TODO: Chequear porque el model.isValid no funciona y hacer que funcione =)
                    model.UserRefId = GetUserId();
                    //TODO: convertir la fecha a UTCs
                    model.Created = DateTime.UtcNow;
                    model.Return = DateTime.UtcNow;
                    model.Modified = DateTime.UtcNow;

                    _repo.Create(model);
                    ViewBag.HasErrors = false;
                    return RedirectToAction("View", "Destination", routeValues: new { id = model.Id });
                }
                ViewBag.InnerException = "Model not valid.";
                ViewBag.HasErrors = true;
                return View(model);
            }
            catch(Exception ex)
            {
                //Log
                ViewBag.InnerException = ex.Message;
                ViewBag.HasErrors = true;
                return View(model);
            }
        }

        // GET: Trip/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                if(id > 0)
                {
                    var trip = _repo.Get(id);
                    return View(trip);
                }
            }
            catch
            {
                //Log
            }
            return View();
        }

        // POST: Trip/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TripModels model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var trip = _repo.Get(id);
                    _repo.Edit(model);
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Trip/Delete/5
        public ActionResult Delete(int id)
        {
            var trips = _repo.Get(id);

            return View(trips);
        }

        // POST: Trip/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, TripModels model)
        {
            try
            {
                if (id > 0)
                {
                    _repo.Delete(id);
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }
            catch(Exception ex) 
            {
                return View();
            }
        }

        private string GetUserId()
        {
            return User.Identity.GetUserId();
        }
    }
}

yourTrip/Views/Trip/Create.cshtml
@model yourTrip.Models.TripModels

@{
    ViewBag.Title = "Create";
    ViewBag.Latitud = "15";
    ViewBag.Longitud = "0";
    ViewBag.Zoom = "2";
    ViewBag.Error = ViewBag.HasErrors ? "display:block;" : "display:none;";
}
<div class="container body-content">
    <h2>First step to plan your trip</h2>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    <div class="row">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 form-horizontal">
            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.Departure, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Departure, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            @*@Html.HiddenFor(model => model.PlaceId, htmlAttributes: new { @id = "placeId", @value = "" })
            @Html.HiddenFor(model => model.Latitud, htmlAttributes: new { @id = "latitud", @value = "" })
            @Html.HiddenFor(model => model.Longitud, htmlAttributes: new { @id = "longitud", @value = "" })*@

            @*<div class="form-group">
                @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div id="locationField">
                        @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @id = "autocomplete", @class = "form-control", @type = "text", placeholder = "Witch city are you going?" } })
                    </div>
                </div>
            </div>*@
            
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>

            <div class="form-group">
                <div id="map"></div>
            </div>

            <div class="alert alert-danger alert-dismissible" role="alert" style="@ViewBag.Error">
                @*@Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })*@
                @Html.ValidationMessageFor(model => model.Departure, "", new { @class = "text-danger" })
                @Html.ValidationMessageFor(model => model, "", new { @class = "text-danger", @value = @ViewBag.InnerException })
            </div>

        </div>
        }

        <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
            <div id="mapsImages"></div>
        </div>
    </div>


    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    <!-- Maps Stuff -->
    <div id="listing">
        <table id="resultsTable">
            <tbody id="results"></tbody>
        </table>
    </div>

    <div style="display: none">
        <div id="info-content">
            <table>
                <tr id="iw-url-row" class="iw_table_row">
                    <td id="iw-icon" class="iw_table_icon"></td>
                    <td id="iw-url"></td>
                </tr>
                <tr id="iw-address-row" class="iw_table_row">
                    <td class="iw_attribute_name">Address:</td>
                    <td id="iw-address"></td>
                </tr>
                <tr id="iw-phone-row" class="iw_table_row">
                    <td class="iw_attribute_name">Telephone:</td>
                    <td id="iw-phone"></td>
                </tr>
                <tr id="iw-rating-row" class="iw_table_row">
                    <td class="iw_attribute_name">Rating:</td>
                    <td id="iw-rating"></td>
                </tr>
                <tr id="iw-website-row" class="iw_table_row">
                    <td class="iw_attribute_name">Website:</td>
                    <td id="iw-website"></td>
                </tr>
            </table>
        </div>
    </div>


</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

yourTrip/Views/Trip/Delete.cshtml
@model yourTrip.Models.TripModels

@{
    ViewBag.Title = "Delete";
}
<div class="container body-content">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>TripModels</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Departure)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Departure)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

yourTrip/Views/Trip/Details.cshtml
@model yourTrip.Models.TripModels

@{
    ViewBag.Title = "Details";
    var destination = Model.Destination.ToString().Replace(' ', '+');
}
<link href="~/Content/main.css" rel="stylesheet" />


<div class="container body-content">
    <h2>Your trip start in</h2>
    <div class="row">
        <div class="col-md-6">

            @Html.Partial("_Counter")

            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Destination)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Destination)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Departure)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Departure)
                </dd>
            </dl>

            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
                @Html.ActionLink("Back to List", "Index")
            </p>
        </div>
        <div class="col-md-6">
            <iframe frameborder="0" class="detailMap"
                    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCFigjZClvz9N8z4KeZpBJyCm1eM_A3-nw
                &q=@destination" allowfullscreen></iframe>
        </div>
    </div>
</div>

yourTrip/Views/Trip/Edit.cshtml
@model yourTrip.Models.TripModels

@{
    ViewBag.Title = "Edit";
}
<div class="container body-content">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>TripModels</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            @*<div class="form-group">
                @Html.LabelFor(model => model.Latitud, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Latitud, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Latitud, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Longitud, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Longitud, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Longitud, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Departure, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Departure, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Departure, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

</div>

yourTrip/Views/Trip/Index.cshtml
@model IList<yourTrip.Models.TripModels>

@{
    bool isFuture = ViewBag.IsFuture.Equals("1") ? true : false;
    bool disable = Model.Count() == 0;
}

<main class="container">
    &nbsp;
    <div class="row">
        <div class="col-md-6">
            <div class="alert alert-secondary" >
                <p class="lead">
                    @using (Html.BeginForm("Create", "Trip", FormMethod.Post, new { @class = "" }))
                    {
                        <div class="form-item">
                            @Html.Editor("Name", new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Trip Name" } })    
                        </div>
                        <div class="form-item">
                            @Html.Editor("Departure", new { htmlAttributes = new { @class = "form-control", @type = "datetime-local", @placeholder = "Pic a date" } })
                        </div>
                        <button type="submit" class="btn btn-block btn-light-blue">Start!</button>
                    }
                </p>
            </div>
        </div>
        <div class="col-md-6">
            @Html.Partial("_Counter")
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @Html.ActionLink("Incoming trips", "Index", "Trip", new { future = true }, new { @class = " " }) |
            @Html.ActionLink("Past trips", "Index", "Trip", new { future = false }, new { @class = "" })
        </div>
    </div>
    &nbsp;
    <div class="row">
        <div class="col-lg-12">
            <div class="card-deck">
            @if (Model.Count() > 0)
            {
                foreach (var item in Model)
                { 
                    <a href="#">
                        <div class="card text-center">
                            <div class="card-body">
                                <h5 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h5>
                                <p class="card-text">@Html.DisplayFor(modelItem => item.Departure.Date)</p>
                                <p class="card-text">
                                    <small class="text-muted">
                                        @Html.ActionLink(linkText: "See", actionName: "View", controllerName: "Destination", routeValues: new { id = item.Id }, htmlAttributes: null)
                                        | @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                    </small>
                                </p>
                            </div>
                        </div>
                    </a>
                }
            }
            else
            {
                <div class="card-body">
                    <h5 class="card-title">Ups!</h5>
                    <p class="card-text">You don't have any incomming trip.</p>
                    <p class="card-text"><small class="text-muted">@Html.ActionLink("Let's create one!", "Create", "Trip")</small></p>
                </div>
            }
            </div>
        </div>
    </div>
</main>

yourTrip/Views/Trip/_Counter.cshtml
<link href="https://fonts.googleapis.com/css?family=Bungee+Hairline|Lobster" rel="stylesheet">

<script src="~/Scripts/clock/jquery-3.2.1.min.js"></script>
<script src="~/Scripts/clock/jquery.countdown.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js"></script>

@if (!string.IsNullOrEmpty(ViewBag.Date))
{
    <div class="alert alert-secondary text-center" role="alert">
        <h3><strong>@ViewBag.TripName</strong> starts in</h3>
        <div class="main-example">
            <div class="countdown-container" id="main-example"></div>
        </div>
    </div>    
<script type="text/template" id="main-example-template">
<div class="time <%= label %>">
    <span class="count curr top"><%= curr %></span>
    <span class="count next top"><%= next %></span>
    <span class="count next bottom"><%= next %></span>
    <span class="count curr bottom"><%= curr %></span>
    <span class="label"><%= label.length < 6 ? label : label.substr(0, 3)  %></span>
</div>
</script>
<script type="text/javascript">
  $(window).on('load', function() {
    var labels = ['weeks', 'days', 'hours', 'minutes', 'seconds'],
      nextYear = '@ViewBag.Date',
      template = _.template($('#main-example-template').html()),
      currDate = '00:00:00:00:00',
      nextDate = '00:00:00:00:00',
      parser = /([0-9]{2})/gi,
      $example = $('#main-example');
    // Parse countdown string to an object
    function strfobj(str) {
      var parsed = str.match(parser),
        obj = {};
      labels.forEach(function(label, i) {
        obj[label] = parsed[i]
      });
      return obj;
    }
    // Return the time components that diffs
    function diff(obj1, obj2) {
      var diff = [];
      labels.forEach(function(key) {
        if (obj1[key] !== obj2[key]) {
          diff.push(key);
        }
      });
      return diff;
    }
    // Build the layout
    var initData = strfobj(currDate);
    labels.forEach(function(label, i) {
      $example.append(template({
        curr: initData[label],
        next: initData[label],
        label: label
      }));
    });
    // Starts the countdown
    $example.countdown(nextYear, function(event) {
      var newDate = event.strftime('%w:%d:%H:%M:%S'),
        data;
      if (newDate !== nextDate) {
        currDate = nextDate;
        nextDate = newDate;
        // Setup the data
        data = {
          'curr': strfobj(currDate),
          'next': strfobj(nextDate)
        };
        // Apply the new values to each node that changed
        diff(data.curr, data.next).forEach(function(label) {
          var selector = '.%s'.replace(/%s/, label),
              $node = $example.find(selector);
          // Update the node
          $node.removeClass('flip');
          $node.find('.curr').text(data.curr[label]);
          $node.find('.next').text(data.next[label]);
          // Wait for a repaint to then flip
          _.delay(function($node) {
            $node.addClass('flip');
          }, 50, $node);
        });
      }
    });
  });
</script>
}
else
{
    <div class="alert alert-secondary text-center" role="alert">
        Ups! You don't have any incomming trip. <br />
        You can create one in the box next to this. 
    </div>
}

yourTrip/Views/Trip/_PhotosPlace.cshtml
https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=CnRtAAAATLZNl354RwP_9UKbQ_5Psy40texXePv4oAlgP4qNEkdIrkyse7rPXYGd9D_Uj1rVsQdWT4oRz4QrYAJNpFX7rzqqMlZw2h2E2y5IKMUZ7ouD_SlcHxYq1yL4KbKUv3qtWgTK0A6QbGh87GB3sscrHRIQiG2RrmU_jF4tENr9wGS_YxoUSSDrYjWmrNfeEHSGSc3FyhNLlBU&key=AIzaSyCFigjZClvz9N8z4KeZpBJyCm1eM_A3-nw

<script>
//llamada a google place API
//obtener los photo_reference 
//llamar a link que esta ahi arriba para obtener la url de la imagen


</script>